services:
    cups:
        build: .
        restart: unless-stopped
        ports:
            - "635:635"
        devices:
            - /dev/bus/usb:/dev/bus/usb
        environment:
            - CUPSADMIN=printeradmin
            - CUPSPASSWORD=print
        volumes:
            - ./cups_config:/etc/cups
            


